HMS/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from hotel import views, AccountViews

urlpatterns = [
    path('admin/', admin.site.urls),
    # path('',include('hotel.urls')),
    path('accounts/', include('allauth.urls')), 
    path('home', views.HomeView, name='HomeView'),

    path('', AccountViews.MainView, name='MainView'),
    path('accounts/profile/', AccountViews.ProfileView, name='ProfileView'),

    path('room_list/', views.RoomListView, name='RoomListView'),
    path('booking_list/', views.BookingListView.as_view(), name='BookingListView'),
    path('meal_list/', views.MealListView, name='MealListView'),
    path('meal_selection_list/', views.MealSelectionList.as_view(), name='MealSelectionList'),
    path('service_list/', views.ServiceListView, name='ServiceListView'),
    path('service_selection_list/', views.ServiceSelectionList.as_view(), name='ServiceSelectionList'), 


    path('room/<category>', views.RoomDetailView.as_view(), name='RoomDetailView'),
    path('meal/<meal_type>', views.MealDetailView.as_view(), name='MealDetailView'),
    path('service/<service_type>', views.ServiceDetailView.as_view(), name='ServiceDetailView'),

    path('booking/cancel/<pk>', views.CancelBookingView.as_view(), name='CancelBookingView'),

    path('payment_add/', views.PaymentCreateView.as_view(), name='PaymentCreateView'),  
    path('payment_list', views.PaymentListView.as_view(), name='PaymentListView'),    

    path('ajax/load-mealcharges/', views.load_mealcharges, name='ajax_load_mealcharges'),
    path('ajax/load-servicecharges/', views.load_servicecharges, name='ajax_load_servicecharges'),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

hotel/urls.py
# from django.urls import path
# from hotel import views
# from .views import HomeView, RoomListView, BookingListView, MealListView, MealSelectionList, ServiceListView, ServiceSelectionList, RoomDetailView, MealDetailView, ServiceDetailView, CancelBookingView

# app_name='hotel'

# urlpatterns=[
#     # path('home', HomeView, name='HomeView'),

#     # path('room_list/', RoomListView, name='RoomListView'),
#     # path('booking_list/', BookingListView.as_view(), name='BookingListView'),
#     # path('meal_list/', MealListView, name='MealListView'),
#     # path('meal_selection_list/', MealSelectionList.as_view(), name='MealSelectionList'),
#     # path('service_list/', ServiceListView, name='ServiceListView'),
#     # path('service_selection_list/', ServiceSelectionList.as_view(), name='ServiceSelectionList'), 


#     # path('room/<category>', RoomDetailView.as_view(), name='RoomDetailView'),
#     # path('meal/<meal_type>', MealDetailView.as_view(), name='MealDetailView'),
#     # path('service/<service_type>', ServiceDetailView.as_view(), name='ServiceDetailView'),

#     # path('booking/cancel/<pk>', CancelBookingView.as_view(), name='CancelBookingView'),

#     # path('ajax/load-mealcharges/', views.load_mealcharges, name='ajax_load_mealcharges'),
# ]

hotel/models.py
from django.db import models
from django.conf import settings
from django.urls import reverse_lazy

# Create your models here.

class Room(models.Model):
    ROOM_CATEGORIES=(
        ('AC', 'Air-Conditioned'),
        ('NAC', 'Non Air-Conditioned'),
        ('DEL', 'Deluxe'),
        ('KIN', 'King'),
        ('QUE', 'Queen'),
    )
    number = models.IntegerField()
    category = models.CharField(max_length=3, choices=ROOM_CATEGORIES)
    beds = models.IntegerField()
    capacity = models.IntegerField()
    room_charge = models.IntegerField()

    def __str__(self):
        return f'{self.number}. {self.category} with {self.beds} beds for {self.capacity} person(s) for {self.room_charge} Shillings'

class Meal(models.Model):
    MEAL_CATEGORIES=(
        ('BRE', 'Breakfast'),
        ('LUN', 'Lunch'),
        ('SUP', 'Supper'), 
    )
    meal_type = models.CharField(max_length=3, choices=MEAL_CATEGORIES)
    meal_name = models.CharField(max_length=20)  

    def __str__(self):
        return f'{self.meal_type}: {self.meal_name}'

class Service(models.Model): 
    SERVICE_CATEGORIES=(
        ('HSKP', 'House Keeping'),
        ('LAUN', 'Laundry'), 
    )
    service_type = models.CharField(max_length=4, choices=SERVICE_CATEGORIES)
    service_name = models.CharField(max_length=20) 

    def __str__(self):
        return f'{self.service_type}: {self.service_name}'

########################################################################################

class MealCharge(models.Model):
    meal = models.ForeignKey(Meal, on_delete=models.CASCADE)
    meal_charge = models.CharField(max_length=30)
 
    def __str__(self):
        return f'{self.meal.meal_name} for {self.meal_charge}'

class ServiceCharge(models.Model):
    service = models.ForeignKey(Service, on_delete=models.CASCADE)
    service_charge = models.CharField(max_length=30)
 
    def __str__(self):
        return f'{self.service.service_name} for {self.service_charge}'
   

########################################################################################

class Booking(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    room = models.ForeignKey(Room, on_delete=models.CASCADE)
    check_in = models.DateTimeField()
    check_out = models.DateTimeField()

    def __str__(self):
        return f'{self.user} has booked room {self.room}; From {self.check_in} To {self.check_out}.' 

    def get_room_category(self):
        room_categories = dict(self.room.ROOM_CATEGORIES)
        room_category = room_categories.get(self.room.category)
        return room_category
    
    def get_cancel_booking_url(self):
        return reverse_lazy('CancelBookingView', args={self.pk, })

class MealSelection(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    meal = models.ForeignKey(Meal, on_delete=models.CASCADE)
    mealcharge = models.ForeignKey(MealCharge, on_delete=models.CASCADE) 
    meal_date = models.DateField()  

    def __str__(self):
        return f'{self.user} has selected {self.meal}; On {self.meal_date}.'  
    
    def get_meal_category(self):
        meal_categories = dict(self.meal.MEAL_CATEGORIES)
        meal_category = meal_categories.get(self.meal.meal_type)
        return meal_category

class ServiceSelection(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    service = models.ForeignKey(Service, on_delete=models.CASCADE)
    servicecharge = models.ForeignKey(ServiceCharge, on_delete=models.CASCADE)
    service_date = models.DateField() 

    def __str__(self):
        return f'{self.user} has selected {self.service}; On {self.service_date}.'  

    def get_service_category(self):
        service_categories = dict(self.service.SERVICE_CATEGORIES)
        service_category = service_categories.get(self.service.service_type)
        return service_category

########################################################################################

class Payment(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    meal = models.ForeignKey(Meal, on_delete=models.SET_NULL, null=True, blank=True, default='')
    mealcharge = models.ForeignKey(MealCharge, on_delete=models.SET_NULL, null=True, blank=True, default='')
    service = models.ForeignKey(Service, on_delete=models.SET_NULL, null=True, blank=True, default='')
    servicecharge = models.ForeignKey(ServiceCharge, on_delete=models.SET_NULL, null=True, blank=True, default='')
    payment_date = models.DateField() 

    def __str__(self):
        return f'Payment By: {self.user} on: {self.payment_date}.'  

    # def get_service_category(self):
    #     service_categories = dict(self.service.SERVICE_CATEGORIES)
    #     service_category = service_categories.get(self.service.service_type)
    #     return service_category
  

hotel/forms.py
from django import forms

from .models import MealSelection, MealCharge, ServiceSelection, ServiceCharge, Payment

class AvailabilityForm(forms.Form):  
    check_in = forms.DateTimeField(required=True, input_formats=["%Y-%m-%dT%H:%M", ])
    check_out = forms.DateTimeField(required=True, input_formats=["%Y-%m-%dT%H:%M", ])


class MealSelectionForm(forms.ModelForm): 
    class Meta:
        model = MealSelection
        fields = ('meal','mealcharge', 'meal_date')
    meal_date = forms.DateField() 

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['mealcharge'].queryset = MealCharge.objects.none()
 
        if 'meal' in self.data:
            try:
                meal_id = int(self.data.get('meal'))
                self.fields['mealcharge'].queryset = MealCharge.objects.filter(meal_id=meal_id)
            except (ValueError, TypeError):
                pass  # invalid input from the client; ignore and fallback to empty City queryset
        elif self.instance.pk:
            self.fields['mealcharge'].queryset = self.instance.meal.mealcharge_set

class ServiceSelectionForm(forms.ModelForm): 
    class Meta:
        model = ServiceSelection
        fields = ('service','servicecharge', 'service_date')
 
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['servicecharge'].queryset = ServiceCharge.objects.none()
 
        if 'service' in self.data:
            try:
                service_id = int(self.data.get('service'))
                self.fields['servicecharge'].queryset = ServiceCharge.objects.filter(service_id=service_id)
            except (ValueError, TypeError):
                pass  # invalid input from the client; ignore and fallback to empty City queryset
        elif self.instance.pk:
            self.fields['servicecharge'].queryset = self.instance.service.servicecharge_set

class PaymentForm(forms.ModelForm): 
    class Meta:
        model = Payment
        fields = ('meal','mealcharge', 'service', 'servicecharge', 'payment_date') 
  
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['mealcharge'].queryset = MealCharge.objects.none()
 
        if 'meal' in self.data:
            try:
                meal_id = int(self.data.get('meal'))
                self.fields['mealcharge'].queryset = MealCharge.objects.filter(meal_id=meal_id)
            except (ValueError, TypeError):
                pass  # invalid input from the client; ignore and fallback to empty City queryset
        elif self.instance.pk:
            self.fields['mealcharge'].queryset = self.instance.meal.mealcharge_set

hotel/templates/availability_form.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Book A Room</title>
</head>
<body>
     <form action="" method="POST">
         {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">Book Room</button>
     </form>
</body>
</html>

hotel/templates/booking_cancel_view.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
	<head>
		<meta charset="UTF-8">
		<meta name="viewport" content="width=device-width, initial-scale=1.0">
        <title>Room Detail</title>
        <script src="https://kit.fontawesome.com/692189991f.js" crossorigin="anonymous"></script>
		<!--main stylesheet -->
		<link rel="stylesheet" href="{% static 'hotel/css/room_detail_view.css' %}">
	</head>
	<body> 
		<!-- main content -->
		<div class="content">
            
            <!--Rom Image-->
            <div class="image">
                <img src="https://images.unsplash.com/photo-1597314040740-5836f612a030?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=500&q=60">
            </div>

            <!--Room Details-->
            <div class="room">

                <!--Div 1 Back to Home-->
                <div class="home">
                     <a href="{% url 'BookingListView' %}"><i class="fas fa-arrow-alt-circle-left">Back</i></a>
                </div>

                <!--Div 2 Room Information-->
                <div class="room-info">
                    <h1>{{ room_category }}</h1>
                    <p>Lorem ipsum dolor sit, amet consectetur adispicing elit. Commodi</p>
                </div>

                <!--Div 3 Room Booking Form-->
                <form id="booking-form" action="" method="POST">
                    {% csrf_token %}
                    <h2>Are you sure you want to cancel the booking? </h2>
                    <p>Details:</p>
                    <p>Room No: {{ booking.room.number }} </p>
                    <p>Type: {{ booking.get_room_category }} </p>
                    <h3>{{ booking }}</h3>
                    <!--Input Div-->
                    <div class="input-div"> 
                        <button type="submit">Cancel The Booking</button>
                    </div>
                </form>
 
            </div>
		</div>  
	</body>
</html>

hotel/templates/booking_list_view.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
    <head>
		<meta charset="UTF-8">
		<meta name="viewport" content="width=device-width, initial-scale=1.0">
		<title>HMS | Bookings</title>
		<!--main stylesheet -->
		<script src="https://kit.fontawesome.com/692189991f.js" crossorigin="anonymous"></script>
		<!--main stylesheet -->
		<link rel="stylesheet" href="{% static 'hotel/css/booking_list_view.css' %}">
    </head>
    <body>
        <div class="content">
            <div class="header">
                <div class="headings">
                    <h1>Your Bookings</h1>
                    <h2>Welcome, Dear {{ user }}</h2>
                </div>
                <div class="home">
                    <!--Div 1: Back to home-->
                    <div class="home">
                        <a href="{% url 'RoomListView' %}"><i class="fas fa-arrow-alt-circle-left">Back</i></a>
                    </div>
                </div>
            </div>

            <div class="bookings">
                {% for booking in booking_list %}
                <div class="booking">
                    <img src="https://images.unsplash.com/photo-1597314040740-5836f612a030?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=500&q=60" alt="">
                    <div class="category">
                        <h2 style="text-align: center;">{{ booking.get_room_category }} </h2>
                    </div>
                    <div class="from">
                        <h3>From: {{ booking.check_in }} </h3>
                    </div>
                    <div class="to">
                        <h3>To: {{ booking.check_out }} </h3>
                    </div>
                    <div class="from">
                        <h3>Room No: {{ booking.room.number }} </h3>
                    </div>
                    <div class="from">
                        <h3>Beds: {{ booking.room.beds }} </h3>
                    </div>
                    <div class="from">
                        <h3>Capacity: {{ booking.room.capacity }} </h3>
                    </div>
                    <div class="from">
                        <h3>Charge: {{ booking.room.room_charge }} KES/-</h3>
                    </div>
                    <div class="cancel">
                        <a href="{{ booking.get_cancel_booking_url }}" class="invisible"><i class="far fa-2x fa-times-circle">Cancel Booking</i></a>
                    </div>
                </div>
                {% endfor %}
            </div>
        </div>
    </body>
</html>

hotel/templates/home_view.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
	<head>
		<meta charset="UTF-8">
		<meta name="viewport" content="width=device-width, initial-scale=1.0">
		<title>HMS | Home</title>
		<!--main stylesheet -->
		<link rel="stylesheet" href="{% static 'hotel/css/home_view.css' %}">
	</head>
	<body>
		<!-- brand -->
		<h1 id="brand">Hotel System</h1>

		<a href="accounts/profile/"><h2 style="text-align: right;">Profile</h2></a>
		<a href="{% url 'PaymentListView' %}"><h2 style="text-align: right;">Payments</h2></a>
		<a href="accounts/logout/"><h4 style="text-align: right;">Logout</h4></a>
		<!-- main content -->
		<div class="content">

			<div class="room">
				<a href="{% url 'RoomListView' %}">
					<img 
					src="https://images.unsplash.com/photo-1590675560125-0d832b9d719e?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=500&q=60" >
					<h2>Rooms</h2>
					<p>Lorem ipsum dolor sit, amet consectetur adispicing elit. Commodi</p>
				</a>
			</div>

			<div class="room">
				<a href="{% url 'MealListView' %}">
					<img 
					src="https://images.unsplash.com/photo-1598614756727-66f0fc8db1e2?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=500&q=60" >
					<h2>Meals</h2>
					<p>Lorem ipsum dolor sit, amet consectetur adispicing elit. Commodi</p>
				</a>
			</div>

			<div class="room">
				<a href="{% url 'ServiceListView' %}">
					<img 
					src="https://images.unsplash.com/photo-1551133990-70307d02dc94?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=500&q=60" >
					<h2>Room Services</h2>
					<p>Lorem ipsum dolor sit, amet consectetur adispicing elit. Commodi</p>
				</a>
			</div>
 
		</div>  
	</body>
</html>

hotel/templates/meal_detail_view.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
  <head>
	  <meta charset="UTF-8">
		<meta name="viewport" content="width=device-width, initial-scale=1.0">
        <title>HMS | Meal Detail</title>
        <script src="https://kit.fontawesome.com/692189991f.js" crossorigin="anonymous"></script>
		<!--main stylesheet -->
		<link rel="stylesheet" href="{% static 'hotel/css/meal_detail_view.css' %}">
	</head>
	<body> 
        <p style="text-align: right;">Logged in as {{ self }}</p>
		<!-- main content -->
		<div class="content">
            
            <!--Rom Image-->
            <div class="image">
                <img src="https://images.unsplash.com/photo-1506084868230-bb9d95c24759?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=500&q=60" width="450" height="500">
            </div>

            <!--Meal Details-->
            <div class="meal">

                <!--Div 1 Back to Home-->
                <div class="home">
                     <a href="{% url 'MealListView' %}"><i class="fas fa-arrow-alt-circle-left">Back</i></a>
                </div>

                <!--Div 2 Meal Information-->
                <div class="meal-info">
                    <h1>{{ meal_category }}</h1>
                    <p>Lorem ipsum dolor sit, amet consectetur adispicing elit. Commodi</p>
                </div>

                <!--Div 3 Meal Selection Form-->
                <form method="post" id="mealselectionForm" data-mealcharges-url="{% url 'ajax_load_mealcharges' %}" novalidate>
                    {% csrf_token %} 
                    
                    {{ mealselectionform }}
                    <!--Input Div-->
                    <div class="input-div"> 
                        <button type="submit">Select Meal</button>
                    </div>
                </form>
            </div>
    </div>  
    <script src="https://code.jquery.com/jquery-3.3.1.min.js"></script>
    <script>
      $("#id_meal").change(function () {
        var url = $("#mealselectionForm").attr("data-mealcharges-url");
        var mealId = $(this).val();
 
        $.ajax({
          url: url,
          data: {
            'meal': mealId
          },
          success: function (data) {
            $("#id_mealcharge").html(data);
          }
        });
 
      });
    </script>

	</body>
</html>

hotel/templates/mealselection_list_view.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
    <head>
		<meta charset="UTF-8">
		<meta name="viewport" content="width=device-width, initial-scale=1.0">
		<title>HMS | Meals Selected</title>
		<!--main stylesheet -->
		<script src="https://kit.fontawesome.com/692189991f.js" crossorigin="anonymous"></script>
		<!--main stylesheet -->
		<link rel="stylesheet" href="{% static 'hotel/css/mealselection_list_view.css' %}">
    </head>
    <body>
        <div class="content">
            <div class="header">
                <div class="headings">
                    <h1>Meals Selected</h1>
                    <h2>Welcome, Dear {{ user }}</h2>
                </div>
                <div class="home">
                    <!--Div 1: Back to home-->
                    <div class="home">
                        <a href="{% url 'MealListView' %}"><i class="fas fa-arrow-alt-circle-left">Back</i></a>
                    </div>
                </div>
            </div>

            <div class="mealselections">
                {% for mealselection in mealselection_list %}
                <div class="mealselection">
                    <img src="https://images.unsplash.com/photo-1543137158-526f3507f08d?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=500&q=60" alt="">
                    <div class="category">
                        <h2>Category: {{ mealselection.get_meal_category }}</h2>
                    </div>
                    <div class="from">
                        <h3>Name: {{ mealselection.meal.meal_name }} </h3>
                    </div>
                    <div class="from">
                        <h3>Price: {{ mealselection.mealcharge.meal_charge }} KES/- </h3>
                    </div>
                    <div class="to">
                        <h3>Date: {{ mealselection.meal_date }} </h3>
                    </div> 
                    <div class="cancel">
                        <a href="#" class="invisible"><i class="far fa-2x fa-times-circle">Cancel Meal</i></a>
                    </div>
                </div>
                {% endfor %}
            </div>
        </div>
    </body>
</html>

hotel/templates/profile_view.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>HMS | Profile</title>
</head>
<body>
    Welcome,
    <br><br>
    <a href="{% url 'HomeView' %}"><h1>Home</h1></a>
    <a href="{% url 'PaymentListView' %}"><h1>Payments</h1></a>

    <br>

    <a href="/accounts/logout/"><h2>Logout</h2></a>
</body>
</html>

hotel/templates/room_detail_view.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
	<head>
		<meta charset="UTF-8">
		<meta name="viewport" content="width=device-width, initial-scale=1.0">
        <title>HMS | Room Detail</title>
        <script src="https://kit.fontawesome.com/692189991f.js" crossorigin="anonymous"></script>
		<!--main stylesheet -->
		<link rel="stylesheet" href="{% static 'hotel/css/room_detail_view.css' %}">
	</head>
	<body> 
        <p style="text-align: right;">Logged in as {{ self }}</p>
		<!-- main content -->
		<div class="content">
            
            <!--Rom Image-->
            <div class="image">
                <img src="https://images.unsplash.com/photo-1598035409965-d88b381d6ce0?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=500&q=60">
            </div>

            <!--Room Details-->
            <div class="room">

                <!--Div 1 Back to Home-->
                <div class="home">
                     <a href="{% url 'RoomListView' %}"><i class="fas fa-arrow-alt-circle-left">Back</i></a>
                </div>

                <!--Div 2 Room Information-->
                <div class="room-info">
                    <h1>{{ room_category }}</h1>
                    <p>Lorem ipsum dolor sit, amet consectetur adispicing elit. Commodi</p>
                </div>

                <!--Div 3 Room Booking Form-->
                <form id="booking-form" action="" method="POST">
                    {% csrf_token %}

                    <!--Input Div-->
                    <div class="input-div">
                        <label for="id_check_in">Check In : </label>
                        <input type="datetime-local" id="id_check_in" name="check_in">
                    </div>
                    <!--Input Div-->
                    <div class="input-div">
                        <label for="id_check_out">Check Out : </label>
                        <input type="datetime-local" id="id_check_out" name="check_out">
                    </div>
                    <!--Input Div-->
                    <div class="input-div"> 
                        <button type="submit">Book Room</button>
                    </div>
                </form>
            </div>
		</div>  
	</body>
</html>

hotel/templates/service_detail_view.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
	<head>
		<meta charset="UTF-8">
		<meta name="viewport" content="width=device-width, initial-scale=1.0">
        <title>HMS | Service Detail</title>
        <script src="https://kit.fontawesome.com/692189991f.js" crossorigin="anonymous"></script>
		<!--main stylesheet -->
		<link rel="stylesheet" href="{% static 'hotel/css/service_detail_view.css' %}">
	</head>
	<body> 
        <p style="text-align: right;">Logged in as {{ self }}</p>
		<!-- main content -->
		<div class="content">
            
            <!--Rom Image-->
            <div class="image">
                <img src="https://images.unsplash.com/photo-1580842402762-6f5868c17412?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=500&q=60" width="500" height="600">
            </div>

            <!--Service Details-->
            <div class="service">

                <!--Div 1 Back to Home-->
                <div class="home">
                     <a href="{% url 'ServiceListView' %}"><i class="fas fa-arrow-alt-circle-left">Back</i></a>
                </div>

                <!--Div 2 Service Information-->
                <div class="service-info">
                    <h1>{{ service_category }}</h1>
                    <p>Lorem ipsum dolor sit, amet consectetur adispicing elit. Commodi</p>
                </div>

                <!--Div 3 Service Selection Form-->
                <form method="post" id="serviceselectionForm" data-servicecharges-url="{% url 'ajax_load_servicecharges' %}" novalidate>
                    {% csrf_token %} 
                    
                    {{ serviceselectionform }}
                    <!--Input Div-->
                    <div class="input-div"> 
                        <button type="submit">Select Service</button>
                    </div>
                </form>
            </div>
        </div> 
        <script src="https://code.jquery.com/jquery-3.3.1.min.js"></script>
        <script>
            $("#id_service").change(function () {
                var url = $("#serviceselectionForm").attr("data-servicecharges-url");
                var serviceId = $(this).val();
 
                $.ajax({
                    url: url,
                    data: {
                        'service': serviceId
                    },
                    success: function (data) {
                    $("#id_servicecharge").html(data);
                }
                });
 
            });
        </script> 
	</body>
</html>

hotel/templates/servicecharge_dropdown_list_options.html
{% for servicecharge in servicecharges %}
<option value="{{ servicecharge.pk }}">{{ servicecharge.service_charge }}</option>
{% endfor %}

hotel/templates/serviceselection_list_view.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
    <head>
		<meta charset="UTF-8">
		<meta name="viewport" content="width=device-width, initial-scale=1.0">
		<title>HMS | Services Selected</title>
		<!--main stylesheet -->
		<script src="https://kit.fontawesome.com/692189991f.js" crossorigin="anonymous"></script>
		<!--main stylesheet -->
		<link rel="stylesheet" href="{% static 'hotel/css/serviceselection_list_view.css' %}">
    </head>
    <body>
        <div class="content">
            <div class="header">
                <div class="headings">
                    <h1>Services Selected</h1>
                    <h2>Welcome, Dear {{ user }}</h2>
                </div>
                <div class="home">
                    <!--Div 1: Back to home-->
                    <div class="home">
                        <a href="{% url 'ServiceListView' %}"><i class="fas fa-arrow-alt-circle-left">Back</i></a>
                    </div>
                </div>
            </div>

            <div class="serviceselections">
                {% for serviceselection in serviceselection_list %}
                <div class="serviceselection">
                    <img src="https://images.unsplash.com/photo-1561024172-0ae2ebd65018?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=500&q=60" alt="">
                    <div class="category">
                        <h2>Category: {{ serviceselection.get_service_category }}</h2>
                    </div>
                    <div class="from">
                        <h3>Name: {{ serviceselection.service.service_name }} </h3>
                    </div>
                    <div class="to">
                        <h3>Date: {{ serviceselection.service_date }} </h3>
                    </div> 
                    <div class="to">
                        <h3>Charge: {{ serviceselection.servicecharge.service_charge }} KES/- </h3>
                    </div> 
                    <div class="cancel">
                        <a href="#" class="invisible"><i class="far fa-2x fa-times-circle">Cancel Service</i></a>
                    </div>
                </div>
                {% endfor %}
            </div>
        </div>
    </body>
</html>